### ISSUE TITLE
does bitprim have reindex function？ 

### ISSUE THREAD

**Issue by Comer2020** [bitprim/bitprim#19]
when I kill bn process or stop it for any reason, then I restart bn, I think it should reindex all the blocks it had downloaded before. But, it alway say: the database directory is already existed and exit. so, my question is how I can restart bn and reuse those blocks already downloaded?

**Comment by fpelliccioni** [comment]
Run `bn -i` just the first time, for DB initialization. Then, the `-i`
argument is no longer needed.
Try just running `bn`.

**Comment by Comer2020** [comment]
oh, cool! 
bn -c my.conf, and it works now.
Another question is that I can not find rpc and zmq port open. Although I config these two port in my config file like this:
[node]
relay_transactions=true
zmq_publisher_port=8913
rpc_port=8915
rpc_allow_ip=127.0.0.1

But, I can not find 8913, 8915 open. 
$netstat -anp | grep 891 | grep LISTEN
tcp        0      0 127.0.0.1:8911          0.0.0.0:*       LISTEN      9885/./bitcoind     
tcp6       0      0 :::8910                 :::*                    LISTEN      9599/geth           
tcp6       0      0 :::8912                 :::*                    LISTEN      10266/./bn     

I install bn by following below instructions: (my system is centos 7)
conan remote add bitprim https://api.bintray.com/conan/bitprim/bitprim
conan install bitprim-node-exe/0.10.2@bitprim/stable

**Comment by Comer2020** [comment]
I find a compile switch in source code:
#ifdef BITPRIM_WITH_RPC
Does this switch affect rpc work? 
How can I do?

**Comment by fpelliccioni** [comment]
You have to install in the following way to have Json-RPC support:

conan install bitprim-node-exe/0.10.2@bitprim/stable -o with_rpc=True

Sorry for the lack of details in the documentation, we are working to
improve it.

Thanks!!

**Comment by Comer2020** [comment]
great!! it works well now.

**Comment by renzobarrionuevo** [comment]
Hi, Livesa. This issue was closed. I recommend you create a new issue for our dev answer your request.
