### ISSUE TITLE
Conan install LTC fail !!

### ISSUE THREAD

**Issue by Comer2020** [bitprim/bitprim#23]
ConanException: Error 32512 while executing cd '/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/4fda6ae25b896ad97951cae3d12e6f7f757e5ed1' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="4.9" -DCONAN_CXX_FLAGS="-m64 -Wno-deprecated-declarations" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/package/4fda6ae25b896ad97951cae3d12e6f7f757e5ed1" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DUSE_CONAN="ON" -DNO_CONAN_AT_ALL="OFF" -DCMAKE_VERBOSE_MAKEFILE="ON" -DENABLE_SHARED="OFF" -DENABLE_POSITION_INDEPENDENT_CODE="ON" -DWITH_TESTS="OFF" -DWITH_EXAMPLES="OFF" -DCURRENCY="LTC" -DWITH_ICU="OFF" -DWITH_QRENCODE="OFF" -DWITH_PNG="OFF" -DNOT_USE_CPP11_ABI="ON" -DBITPRIM_BUILD_NUMBER="-" -Wno-dev '/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/4fda6ae25b896ad97951cae3d12e6f7f757e5ed1'

could you gave me some advices? thank you very much

**Comment by Comer2020** [comment]
my gcc is 4.9.2 and cmake 3.11.2

**Comment by Comer2020** [comment]
and, install BTC by Conan is ok! But, LTC fails

**Comment by fpelliccioni** [comment]
Could you provide the `conan install` line you are running and the full
error log, pleaae?
Thanks.

**Comment by fpelliccioni** [comment]
Cmake greater or equal than 3.4 is required.

https://github.com/bitprim/bitprim/blob/master/README.md#building-from-source-requirements

**Comment by Comer2020** [comment]
[root@iZbp1bjmwh4ypzwl5j9419Z bitprimcon]# conan install bitprim-node-exe/0.10.2@bitprim/stable -o currency=LTC -o with_rpc=True
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 6.3
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI, edit the default profile at:

    ~/.conan/profiles/default

adjusting 'compiler.libcxx=libstdc++11'

************************************************************************************



Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=gcc
	compiler.version=6
	compiler.libcxx=libstdc++
	build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


bitprim-node-exe/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-node-exe/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-node-exe/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 684B/684B        
Downloading conanfile.py
[==================================================] 9.5KB/9.5KB      
Downloading conan_export.tgz
[==================================================] 185B/185B        
*** cpuid could not be imported
*** cpuid could not be imported
bitprim-node-exe/0.10.2@bitprim/stable: Compiling for microarchitecture (default): x86_64
bitprim-node-exe/0.10.2@bitprim/stable: Compiling for currency: LTC
bitprim-node-exe/0.10.2@bitprim/stable: Compiling with RPC support: True
bitprim-node/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-node/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-node/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 5.1KB/5.1KB      
Downloading conanfile.py
[==================================================] 7.8KB/7.8KB      
Downloading conan_export.tgz
[==================================================] 180B/180B        
bitprim-node/0.10.2@bitprim/stable: def config_options(self):
boost/1.66.0@bitprim/stable: Not found in local cache, looking in remotes...
boost/1.66.0@bitprim/stable: Trying with 'conan-center'...
boost/1.66.0@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 58B/58B          
Downloading conanfile.py
[==================================================] 40.9KB/40.9KB    
boost/1.66.0@bitprim/stable: def config_options(self):
boost/1.66.0@bitprim/stable: def configure(self):
boost/1.66.0@bitprim/stable: def requirements(self):
icu/60.2@bitprim/stable: Not found in local cache, looking in remotes...
icu/60.2@bitprim/stable: Trying with 'conan-center'...
icu/60.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 327B/327B        
Downloading conanfile.py
[==================================================] 18.9KB/18.9KB    
bitprim-blockchain/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-blockchain/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-blockchain/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 4.8KB/4.8KB      
Downloading conanfile.py
[==================================================] 7.0KB/7.0KB      
Downloading conan_export.tgz
[==================================================] 180B/180B        
bitprim-database/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-database/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-database/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 6.9KB/6.9KB      
Downloading conanfile.py
[==================================================] 6.5KB/6.5KB      
Downloading conan_export.tgz
[==================================================] 185B/185B        
bitprim-core/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-core/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-core/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 41.7KB/41.7KB    
Downloading conanfile.py
[==================================================] 9.4KB/9.4KB      
Downloading conan_export.tgz
[==================================================] 179B/179B        
bitprim-core/0.10.2@bitprim/stable: def config_options(self):
secp256k1/0.3@bitprim/stable: Not found in local cache, looking in remotes...
secp256k1/0.3@bitprim/stable: Trying with 'conan-center'...
secp256k1/0.3@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 6.0KB/6.0KB      
Downloading conanfile.py
[==================================================] 11.0KB/11.0KB    
Downloading conan_export.tgz
[==================================================] 177B/177B        
gmp/6.1.2@bitprim/stable: Not found in local cache, looking in remotes...
gmp/6.1.2@bitprim/stable: Trying with 'conan-center'...
gmp/6.1.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 58B/58B          
Downloading conanfile.py
[==================================================] 14.7KB/14.7KB    
gmp/6.1.2@bitprim/stable: Provided microarchitecture (user defined): x86_64
OpenSSL/1.0.2l@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2l@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 58B/58B          
Downloading conanfile.py
[==================================================] 18.1KB/18.1KB    
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 121B/121B        
Downloading conanfile.py
[==================================================] 7.7KB/7.7KB      
bitprim-consensus/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-consensus/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-consensus/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 6.8KB/6.8KB      
Downloading conanfile.py
[==================================================] 6.9KB/6.9KB      
Downloading conan_export.tgz
[==================================================] 180B/180B        
bitprim-network/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-network/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-network/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 5.2KB/5.2KB      
Downloading conanfile.py
[==================================================] 6.4KB/6.4KB      
Downloading conan_export.tgz
[==================================================] 185B/185B        
bitprim-network/0.10.2@bitprim/stable: def config_options(self):
bitprim-rpc/0.10.2@bitprim/stable: Not found in local cache, looking in remotes...
bitprim-rpc/0.10.2@bitprim/stable: Trying with 'conan-center'...
bitprim-rpc/0.10.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 4.4KB/4.4KB      
Downloading conanfile.py
[==================================================] 6.9KB/6.9KB      
Downloading conan_export.tgz
[==================================================] 180B/180B        
bitprim-rpc/0.10.2@bitprim/stable: def config_options(self):
libzmq/4.2.2@bitprim/stable: Not found in local cache, looking in remotes...
libzmq/4.2.2@bitprim/stable: Trying with 'conan-center'...
libzmq/4.2.2@bitprim/stable: Trying with 'bitprim'...
Downloading conanmanifest.txt
[==================================================] 109B/109B        
Downloading conanfile.py
[==================================================] 7.7KB/7.7KB      
Downloading conan_export.tgz
[==================================================] 941B/941B        
libzmq/4.2.2@bitprim/stable: *-*-*-*-*-* def config_options(self):
bitprim-core/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-database/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-blockchain/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-rpc/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-node/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-network/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-consensus/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-node-exe/0.10.2@bitprim/stable: Building package from source as defined by build_policy='missing'
bitprim-node-exe/0.10.2@bitprim/stable: Installing package
Requirements
    OpenSSL/1.0.2l@conan/stable from 'conan-center' - Downloaded
    bitprim-blockchain/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-consensus/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-core/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-database/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-network/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-node/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-node-exe/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    bitprim-rpc/0.10.2@bitprim/stable from 'bitprim' - Downloaded
    boost/1.66.0@bitprim/stable from 'bitprim' - Downloaded
    gmp/6.1.2@bitprim/stable from 'bitprim' - Downloaded
    icu/60.2@bitprim/stable from 'bitprim' - Downloaded
    libzmq/4.2.2@bitprim/stable from 'bitprim' - Downloaded
    secp256k1/0.3@bitprim/stable from 'bitprim' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    OpenSSL/1.0.2l@conan/stable:b26292e72029cbb49954e281042054a0225df24d - Download
    bitprim-blockchain/0.10.2@bitprim/stable:7a659ccc0af9584345f059b0521301031fdf7cbd - Build
    bitprim-consensus/0.10.2@bitprim/stable:7b1129331672bf3393b694e9df16811afb7b9d08 - Build
    bitprim-core/0.10.2@bitprim/stable:640a3024518584ec166796880aa70f0c13ec9484 - Build
    bitprim-database/0.10.2@bitprim/stable:dd3ca0f561ae767916cc05cb5b1dbf4899f3aff5 - Build
    bitprim-network/0.10.2@bitprim/stable:c1f30932e40690d494efc2262ce464600601e2db - Build
    bitprim-node/0.10.2@bitprim/stable:fcf716887269d74e7ecfcd97b8d5b220460d78cf - Build
    bitprim-node-exe/0.10.2@bitprim/stable:4b5652d48c38850ebf45fba8144e67d5bfe3aa34 - Build
    bitprim-rpc/0.10.2@bitprim/stable:1e6362f648d7f0e04fb57dce7e19de6ca292e5b5 - Build
    boost/1.66.0@bitprim/stable:09be9e7c0ff541e3d176724da4fcb1dc502449d4 - Download
    gmp/6.1.2@bitprim/stable:9d45ddcb99ad364442dca0388efb53813f8babc8 - Download
    icu/60.2@bitprim/stable:e472b3a77729e820ab438e3fa74598311bc9eafe - Download
    libzmq/4.2.2@bitprim/stable:55d8b5ce2a82d1dc5b00cedc6b8c0c4e39336056 - Download
    secp256k1/0.3@bitprim/stable:bca813344a6ddc4d5fcfea2c08556f99368b7a6e - Download
    zlib/1.2.11@conan/stable:351053dac39760023a2758a781ec2b142ea75835 - Download

gmp/6.1.2@bitprim/stable: Retrieving package 9d45ddcb99ad364442dca0388efb53813f8babc8 from remote 'bitprim' 
Downloading conanmanifest.txt
[==================================================] 9.0KB/9.0KB      
Downloading conaninfo.txt
[==================================================] 678B/678B        
Downloading conan_package.tgz
[==================================================] 855.9KB/855.9KB  
gmp/6.1.2@bitprim/stable: Package installed 9d45ddcb99ad364442dca0388efb53813f8babc8
icu/60.2@bitprim/stable: Retrieving package e472b3a77729e820ab438e3fa74598311bc9eafe from remote 'bitprim' 
Downloading conanmanifest.txt
[==================================================] 13.2KB/13.2KB    
Downloading conaninfo.txt
[==================================================] 580B/580B        
Downloading conan_package.tgz
[==================================================] 29.7MB/29.7MB    
icu/60.2@bitprim/stable: Package installed e472b3a77729e820ab438e3fa74598311bc9eafe
libzmq/4.2.2@bitprim/stable: Retrieving package 55d8b5ce2a82d1dc5b00cedc6b8c0c4e39336056 from remote 'bitprim' 
Downloading conanmanifest.txt
[==================================================] 259B/259B        
Downloading conaninfo.txt
[==================================================] 479B/479B        
Downloading conan_package.tgz
[==================================================] 439.4KB/439.4KB  
libzmq/4.2.2@bitprim/stable: Package installed 55d8b5ce2a82d1dc5b00cedc6b8c0c4e39336056
zlib/1.2.11@conan/stable: Retrieving package 351053dac39760023a2758a781ec2b142ea75835 from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 800B/800B        
Downloading conaninfo.txt
[==================================================] 364B/364B        
Downloading conan_package.tgz
[==================================================] 125.1KB/125.1KB  
zlib/1.2.11@conan/stable: Package installed 351053dac39760023a2758a781ec2b142ea75835
OpenSSL/1.0.2l@conan/stable: Retrieving package b26292e72029cbb49954e281042054a0225df24d from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 4.6KB/4.6KB      
Downloading conaninfo.txt
[==================================================] 1.1KB/1.1KB      
Downloading conan_package.tgz
[==================================================] 2.0MB/2.0MB      
OpenSSL/1.0.2l@conan/stable: Package installed b26292e72029cbb49954e281042054a0225df24d
boost/1.66.0@bitprim/stable: Retrieving package 09be9e7c0ff541e3d176724da4fcb1dc502449d4 from remote 'bitprim' 
Downloading conanmanifest.txt
[==================================================] 1.1MB/1.1MB      
Downloading conaninfo.txt
[==================================================] 2.3KB/2.3KB      
Downloading conan_package.tgz
[==================================================] 15.1MB/15.1MB    
boost/1.66.0@bitprim/stable: Package installed 09be9e7c0ff541e3d176724da4fcb1dc502449d4
boost/1.66.0@bitprim/stable: Missing in order: boost_log_setup
boost/1.66.0@bitprim/stable: Missing in order: boost_test_exec_monitor
boost/1.66.0@bitprim/stable: Missing in order: boost_prg_exec_monitor
boost/1.66.0@bitprim/stable: Missing in order: boost_unit_test_framework
boost/1.66.0@bitprim/stable: LIBRARIES: ['boost_exception', 'boost_iostreams', 'boost_locale', 'boost_log', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_timer', 'boost_thread', 'boost_chrono', 'boost_date_time', 'boost_atomic', 'boost_filesystem', 'boost_system', 'boost_log_setup', 'boost_unit_test_framework', 'rt']
boost/1.66.0@bitprim/stable: Package folder: /root/.conan/data/boost/1.66.0/bitprim/stable/package/09be9e7c0ff541e3d176724da4fcb1dc502449d4
secp256k1/0.3@bitprim/stable: Retrieving package bca813344a6ddc4d5fcfea2c08556f99368b7a6e from remote 'bitprim' 
Downloading conanmanifest.txt
[==================================================] 350B/350B        
Downloading conaninfo.txt
[==================================================] 1.3KB/1.3KB      
Downloading conan_package.tgz
[==================================================] 55.0KB/55.0KB    
secp256k1/0.3@bitprim/stable: Package installed bca813344a6ddc4d5fcfea2c08556f99368b7a6e
Downloading conan_sources.tgz
[==================================================] 522.8KB/522.8KB  
bitprim-core/0.10.2@bitprim/stable: Building your package in /root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/640a3024518584ec166796880aa70f0c13ec9484
bitprim-core/0.10.2@bitprim/stable: Configuring sources in /root/.conan/data/bitprim-core/0.10.2/bitprim/stable/source
bitprim-core/0.10.2@bitprim/stable: Copying sources to build folder
bitprim-core/0.10.2@bitprim/stable: Generator cmake created conanbuildinfo.cmake
bitprim-core/0.10.2@bitprim/stable imports(): Copied 536 '.h' files: 
bitprim-core/0.10.2@bitprim/stable: Calling build()
boost
<conans.model.options.PackageOptionValues object at 0x7fd900ec6e50>
secp256k1
<conans.model.options.PackageOptionValues object at 0x7fd900e5c1d0>
OpenSSL
<conans.model.options.PackageOptionValues object at 0x7fd900f0a990>
icu
<conans.model.options.PackageOptionValues object at 0x7fd900e5c5d0>
gmp
<conans.model.options.PackageOptionValues object at 0x7fd900e5c650>
zlib
<conans.model.options.PackageOptionValues object at 0x7fd900e5c690>
sh: cmake: 未找到命令
bitprim-core/0.10.2@bitprim/stable: 
bitprim-core/0.10.2@bitprim/stable: ERROR: Package '640a3024518584ec166796880aa70f0c13ec9484' build failed
bitprim-core/0.10.2@bitprim/stable: WARN: Build folder /root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/640a3024518584ec166796880aa70f0c13ec9484
ERROR: bitprim-core/0.10.2@bitprim/stable: Error in build() method, line 201
	cmake.configure(source_dir=self.source_folder)
	ConanException: Error 32512 while executing cd '/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/640a3024518584ec166796880aa70f0c13ec9484' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="6" -DCONAN_CXX_FLAGS="-m64 -Wno-deprecated-declarations" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/package/640a3024518584ec166796880aa70f0c13ec9484" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DUSE_CONAN="ON" -DNO_CONAN_AT_ALL="OFF" -DCMAKE_VERBOSE_MAKEFILE="ON" -DENABLE_SHARED="OFF" -DENABLE_POSITION_INDEPENDENT_CODE="ON" -DWITH_TESTS="OFF" -DWITH_EXAMPLES="OFF" -DCURRENCY="LTC" -DWITH_ICU="OFF" -DWITH_QRENCODE="OFF" -DWITH_PNG="OFF" -DNOT_USE_CPP11_ABI="OFF" -DBITPRIM_BUILD_NUMBER="-" -Wno-dev '/root/.conan/data/bitprim-core/0.10.2/bitprim/stable/build/640a3024518584ec166796880aa70f0c13ec9484'
[root@iZbp1bjmwh4ypzwl5j9419Z bitprimcon]#

**Comment by Comer2020** [comment]
[root@iZbp1bjmwh4ypzwl5j9419Z bitprimcon]# cmake3 -version
cmake3 version 3.11.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by Comer2020** [comment]
oh, I see. maybe I should make a link cmake to cmake3

**Comment by Comer2020** [comment]
cannon cannot find cmake.
it works now, thanks!
