### ISSUE TITLE
Does Bitprim LTC version support testnetv4 ?

### ISSUE THREAD

**Issue by Comer2020** [bitprim/bitprim#24]
it seems that current 0.10.2 LTC can not synchronize blocks in testnet. I find it will stop synchronizing at block height 14666.

**Comment by fpelliccioni** [comment]
Thanks for reporting it.
We will check it as soon as possible.

Kind regard,

**Comment by Comer2020** [comment]
it seems some config is not correct. now, it works. thanks!
