### ISSUE TITLE
ERROR: Package '755cd4c43ec98347e79c58bb358acf5edffaf479' build failed

### ISSUE THREAD

**Issue by Jeanluis019** [bitprim/bitprim#8]
Hello! I get this problem when I run "conan install ." to install "conanfile.txt"

Can anyone help me, please?

I'm following the below tutorial to install bitprim: 
[https://www.bitprim.org/installation.html](url)

Error:

> secp256k1/0.3@bitprim/stable: ERROR: Package '755cd4c43ec98347e79c58bb358acf5edffaf479' build failed
secp256k1/0.3@bitprim/stable: WARN: Build folder /Users/MYUSER/.conan/data/secp256k1/0.3/bitprim/stable/build/755cd4c43ec98347e79c58bb358acf5edffaf479
ERROR: secp256k1/0.3@bitprim/stable: Error in build() method, line 263
	cmake.configure(source_dir=self.source_folder)
	ConanException: Error 32512 while executing cd '/Users/MYUSER/.conan/data/secp256k1/0.3/bitprim/stable/build/755cd4c43ec98347e79c58bb358acf5edffaf479' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="9.1" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/MYUSER/.conan/data/secp256k1/0.3/bitprim/stable/package/755cd4c43ec98347e79c58bb358acf5edffaf479" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DUSE_CONAN="ON" -DNO_CONAN_AT_ALL="OFF" -DCMAKE_VERBOSE_MAKEFILE="OFF" -DENABLE_SHARED="OFF" -DENABLE_POSITION_INDEPENDENT_CODE="ON" -DENABLE_BENCHMARK="OFF" -DENABLE_TESTS="OFF" -DENABLE_OPENSSL_TESTS="OFF" -DENABLE_EXPERIMENTAL="OFF" -DENABLE_ENDOMORPHISM="OFF" -DENABLE_ECMULT_STATIC_PRECOMPUTATION="OFF" -DENABLE_MODULE_ECDH="OFF" -DENABLE_MODULE_SCHNORR="OFF" -DENABLE_MODULE_RECOVERY="ON" -DWITH_BIGNUM="gmp" -DBITPRIM_BUILD_NUMBER="-" -Wno-dev '/Users/MYUSER/.conan/data/secp256k1/0.3/bitprim/stable/build/755cd4c43ec98347e79c58bb358acf5edffaf479'

**Comment by fpelliccioni** [comment]
Hello!

These instructions became obsolete, sorry. We have to remove that page.

Please follow the following  instructions:

https://github.com/bitprim/bitprim/blob/master/README.md#installation-procedure

Please tell me if it worked well. 

Sorry for the inconvenient.

Best Regards.

**Comment by Jeanluis019** [comment]
Yeah! now it's working. Thank you!

**Comment by ztlovemst11** [comment]
but there are new problem here
